# -*- coding: utf-8 -*-
"""Process2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T9EBhMPJLH2a8rg0kTKRX3sMZ1vA6PAz
"""

import os
import requests
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Get API key and URL from environment variables
api_key = os.getenv("TOLLGURU_API_KEY")
api_url = os.getenv("TOLLGURU_API_URL")

# Check if API key and URL are present
if not api_key or not api_url:
    raise ValueError("https://apis.tollguru.com/toll/v2/gps-tracks-csv-upload?mapProvider=osrm")

# API endpoint for GPS tracks CSV upload
endpoint = f"{api_url}/gps-tracks-csv-upload"

# API parameters
params = {
    "vehicleType": "5AxlesTruck",
    "mapProvider": "osrm",
}

# Sample CSV file (replace this with the actual path to your CSV file)
csv_file_path = "path/to/your/gps_tracks.csv"

# Open and read the CSV file as binary
with open(csv_file_path, "rb") as csv_file:
    # Prepare headers
    headers = {
        "Content-Type": "application/octet-stream",
        "Authorization": f"Bearer {api_key}",
    }

    # Make the API request
    response = requests.post(endpoint, params=params, headers=headers, data=csv_file)

# Check the response
if response.status_code == 200:
    # Parse and print the JSON response
    json_response = response.json()
    print(json_response)
else:
    print(f"Error {response.status_code}: {response.text}")