# -*- coding: utf-8 -*-
"""process1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pY378Mi5b4kzFeSWOpmhSgFoihUPQaCa
"""

import pandas as pd

# GitHub raw link to the Parquet file
github_link = 'https://github.com/mapup/MapUp-Data-Assessment-E/raw/main/evaluation_data/input/raw_data.parquet'

# Read Parquet file from GitHub using pandas
df = pd.read_parquet(github_link)

# Display the DataFrame
print(df.head())

# -*- coding: utf-8 -*-
"""process1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mgRE5ryEIsjib2cNGRKEGRKdQRALrkfC
"""

import pandas as pd

# GitHub raw link to the Parquet file
github_link = 'https://github.com/mapup/MapUp-Data-Assessment-E/raw/main/evaluation_data/input/raw_data.parquet'

# Read Parquet file from GitHub using pandas
df = pd.read_parquet(github_link)

# Display the DataFrame
print(df.head())

df.shape

df.info()

df.tail()

import pandas as pd

df['timestamp'] = pd.to_datetime(df['timestamp'])
time_diff = df['timestamp'].diff()
selected_rows = df[time_diff > pd.Timedelta(hours=7)]
print(selected_rows)

import pandas as pd

selected_rows_1 = df.iloc[0:14644]
selected_rows_1.to_csv('1000_trip_number_1.csv', index=False)

selected_rows_2 = df.iloc[14645:26924]
selected_rows_2.to_csv('1000_trip_number_2.csv', index=False)

selected_rows_3 = df.iloc[26925:42778]
selected_rows_3.to_csv('1000_trip_number_3.csv', index=False)

selected_rows_4 = df.iloc[42779:46500]
selected_rows_4.to_csv('1000_trip_number_4.csv', index=False)

selected_rows_5 = df.iloc[46501:58802]
selected_rows_5.to_csv('2000_trip_number_1.csv', index=False)

selected_rows_6 = df.iloc[58803:62262]
selected_rows_6.to_csv('2000_trip_number_2.csv', index=False)

selected_rows_7 = df.iloc[62263:73471]
selected_rows_7.to_csv('2000_trip_number_3.csv', index=False)

from google.colab import files

files.download('1000_trip_number_1.csv')
files.download('1000_trip_number_2.csv')
files.download('1000_trip_number_3.csv')
files.download('1000_trip_number_4.csv')
files.download('2000_trip_number_1.csv')
files.download('2000_trip_number_2.csv')
files.download('2000_trip_number_3.csv')